/** Tailwind config — tokens 1:1 del design system de Google Stitch (PulsePath). */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#444655',
        'on-background': '#131b2e',
        'primary-fixed-dim': '#b8c3ff',
        'on-surface': '#131b2e',
        'surface-dim': '#d2d9f4',
        'surface-variant': '#dae2fd',
        'secondary-fixed-dim': '#bfc6dd',
        primary: '#264dd9',
        'outline-variant': '#c4c5d7',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed': '#001355',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-container': '#f5fff6',
        error: '#ba1a1a',
        'surface-bright': '#faf8ff',
        'surface-container': '#eaedff',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        background: '#faf8ff',
        'primary-container': '#4568f3',
        'tertiary-container': '#00855b',
        'on-secondary': '#ffffff',
        'inverse-surface': '#283044',
        'primary-fixed': '#dde1ff',
        'on-tertiary-fixed': '#002113',
        'on-secondary-fixed': '#141b2c',
        'surface-tint': '#294fdb',
        'on-secondary-fixed-variant': '#3f4759',
        surface: '#faf8ff',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#dbe2fa',
        'surface-container-high': '#e2e7ff',
        tertiary: '#006947',
        'inverse-on-surface': '#eef0ff',
        'tertiary-fixed': '#6ffbbe',
        'secondary-container': '#dbe2fa',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-container': '#fffbff',
        'surface-container-highest': '#dae2fd',
        'on-secondary-container': '#5d6478',
        'on-primary-fixed-variant': '#0035bd',
        secondary: '#575e72',
        outline: '#747686',
        'surface-container-low': '#f2f3ff',
        'inverse-primary': '#b8c3ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '120px',
        xs: '8px',
        lg: '48px',
        gutter: '24px',
        md: '24px',
        'margin-mobile': '16px',
        xl: '80px',
        sm: '16px',
        base: '4px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-xl': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
